name: gf_attendance
description: GaonFR Kids Attendance Management System - Flutter App
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Layout
  cupertino_icons: ^1.0.6
  flutter_screenutil: ^5.9.0

  # State Management
  provider: ^6.1.1

  # HTTP & API Communication
  http: ^1.1.0
  dio: ^5.4.0

  # Local Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0

  # Camera & Face Recognition
  camera: ^0.10.5+5
  google_mlkit_face_detection: ^0.9.0

  # Permissions
  permission_handler: ^11.1.0

  # Device Information
  device_info_plus: ^9.1.1
  package_info_plus: ^4.2.0

  # Date & Time
  intl: ^0.18.1

  # Additional Utilities
  path_provider: ^2.1.1
  image: ^4.1.3

  # Audio Support
  audioplayers: ^5.2.1
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/